[project]
name = "aw-watcher-buttons"
version = "0.0.1"
description = "Hardware buttons watcher for ActivityWatch"
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE.txt" }
authors = [{ name = "Zach Strout", email = "zachstrout@gmail.com" }]
dependencies = [
  "aw-client>=0.5.7",
  "pyserial>=3.5",
]

[project.urls]
Repository = "https://github.com/RTnhN/aw-watcher-buttons"

[project.scripts]
aw-watcher-buttons = "aw_watcher_buttons:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
